services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Disjfa\MediaBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests}'

    Disjfa\MediaBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

#    Disjfa\MediaBundle\Security\:
#        resource: './../../Security/*'
#        tags: ['security.voter']

    Disjfa\MediaBundle\Service\UploadService:
        $uploadPath: '%env(UPLOAD_PATH)%'
        $rootDir: '%kernel.project_dir%'

    Disjfa\MediaBundle\Menu\AdminMediaMenuListener:
        autowire: true
        tags:
        - { name: 'kernel.event_listener', event: 'admin.menu_configure', method: 'onMenuConfigure', priority: -50 }
